server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/meeting
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.yangcc.entity
  configuration:
    map-underscore-to-camel-case: true

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
# 验证图相关
aj:
  captcha:
    type: default
    jigsaw: classpath:images/jigsaw
    pic-click: classpath:images/pic-click
    water-mark: login
    slip-offset: 5
    aes-status: true
    interference-options: 0
    history-data-clear-enable: true
    req-frequency-limit-enable: true
    req-get-lock-limit: 5
    req-get-lock-seconds: 360
    req-get-minute-limit: 30
    req-check-minute-limit: 60
    req-verify-minute-limit: 60
